apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}
  ports:
  - protocol: {{ .Values.protocol }}
    port: {{ .Values.port }}
    targetPort: {{ .Values.targetPort }}