variable "vnet" {}
variable "rgs" {}
variable "subnet" {}
variable "storage" {}
variable "vms" {}
variable "nic" {}
variable "acr" {}
variable "aks" {}
variable "sql_server" {}
variable "db_server" {}
variable "kv" {}